name: one_health_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  bloc: ^8.0.3
  bottom_navy_bar: ^6.0.0
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_onboarding_slider: ^1.0.7
  google_fonts: ^3.0.0
  iconify_flutter: ^0.0.4
  image_picker: ^0.8.5+3
  lottie: ^1.3.0
  page_transition: ^2.0.5
  pinput: ^2.2.9
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/LOTTIE/hospitallogin.json
    - assets/LOTTIE/forgotpassword.json
